version: 2.1

jobs:
  build-web:
    steps:
      - checkout
      - run:
          name: build web 
          command: ./build_web.sh
      - store_artifacts:
          path: ~/project/target/web
          destination: w
      - run:
          name: Install Butler
          command: |
            curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
            unzip butler.zip
            chmod +x butler
            ./butler -V
      - run:
          name: Push to Itch.io
          command: ./butler push ~/project/target/web ThermalSpan/spirograph:${CIRCLE_BRANCH}

workflows:
  version: 2
  build:
    jobs:
      - build-web
